### ISSUE TITLE
Database schema naming style

### ISSUE THREAD

**Issue by a-komarev** [yii2mod/yii2-cron-log#3]
I understand that all is a matter of taste, but most of all modules and components on Yii2 using database table names in lowercase like `cron_schedule` and lowercase columns names `job_code`.
If you want, I can prepare pull request for your component to fit the naming conventions.

For example you can look at default yii migration table.
```
CREATE TABLE `migration` (
	`version` VARCHAR(180) NOT NULL,
	`apply_time` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`version`)
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB;
```

**Comment by disem** [comment]
Sorry, but CamelCase for tables naming and lowerCamelCase for fields is our company standart, and this extensions are part of our projects which must follow our internal code agreement.

**Comment by a-komarev** [comment]
I understand, it's pretty usual case.
