### ISSUE TITLE
Where can I find parameters

### ISSUE THREAD

**Issue by philippfrenzel** [yii2mod/yii2-cron-log#8]
Hi, 

do you log the parameters passed to the cron job too??

Thanks Philipp

**Comment by igor-chepurnoi** [comment]
Hi, in [this line](https://github.com/yii2mod/yii2-cron-log/blob/master/behaviors/CronLoggerBehavior.php#L73) we get the command code and the parameters

**Comment by philippfrenzel** [comment]
great - thanks!
